# Generated by Django 2.0 on 2017-12-08 11:38

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Заметка для того, чтобы отличать одни контакты от других. К примеру, "Основные контакты" или "Запасной вариант".', max_length=100, verbose_name='Подпись')),
                ('email', models.CharField(blank=True, max_length=200, null=True, verbose_name='Email')),
                ('contacts_phone', models.CharField(blank=True, max_length=90, null=True, verbose_name='Телефон/ы на странице контактов')),
                ('footer_phone', models.CharField(blank=True, max_length=90, null=True, verbose_name='Телефон в нижней части страници')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Адрес')),
                ('addressHref', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ссылка перенаправляющая на карты(Google/Yandex)')),
                ('map', models.TextField(blank=True, help_text='Карта, которая отображается в контактах', max_length=1024, null=True, verbose_name='Окно с картой')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
                'db_table': 'site_contacts',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Имя настройки')),
                ('widgets', models.TextField(blank=True, max_length=8196, null=True, verbose_name='Метрики, виджеты и прочее')),
                ('meta', models.TextField(blank=True, max_length=300, null=True, verbose_name='Глобальное META-описание сайта')),
                ('title', models.CharField(blank=True, max_length=90, null=True, verbose_name='Заголовок сайта/страницы')),
                ('default_link_color', colorfield.fields.ColorField(blank=True, max_length=18, null=True, verbose_name='Стандартный цвет ссылок')),
                ('default_link_hover_color', colorfield.fields.ColorField(blank=True, max_length=18, null=True, verbose_name='Стандартный цвет ссылок при наведении')),
                ('menu_link_active_color', colorfield.fields.ColorField(blank=True, max_length=18, null=True, verbose_name='Цвет шрифта активной ссылки')),
                ('menu_link_hover_bg', colorfield.fields.ColorField(blank=True, max_length=18, null=True, verbose_name='Цвет фона ссылок при наведении')),
                ('default_color', colorfield.fields.ColorField(blank=True, max_length=18, null=True, verbose_name='Цвет шрифта по умолчанию')),
                ('default_bg', colorfield.fields.ColorField(blank=True, max_length=18, null=True, verbose_name='Цвет фона сайта')),
                ('default_image_bg', colorfield.fields.ColorField(blank=True, max_length=18, null=True, verbose_name='Фоновое изображение сайта')),
                ('preloader_color', colorfield.fields.ColorField(blank=True, max_length=18, null=True, verbose_name='Цвет прелоадера')),
                ('curtain_bg', colorfield.fields.ColorField(blank=True, max_length=18, null=True, verbose_name='Цвет фона предварительной загрузки')),
            ],
            options={
                'verbose_name': 'Настройка',
                'verbose_name_plural': 'Настройки',
                'db_table': 'site_settings',
            },
        ),
    ]
