# Generated by Django 2.0 on 2017-12-08 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='title',
        ),
        migrations.AddField(
            model_name='settings',
            name='contacts',
            field=models.ForeignKey(blank=True, help_text='Укажите контакты, которые хотите отобразить', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_contacts', to='app.Contacts', verbose_name='Контакты'),
        ),
    ]
