# Generated by Django 2.0 on 2017-12-08 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20171208_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='default_image_bg',
            field=models.ImageField(blank=True, null=True, upload_to='background/', verbose_name='Фоновое изображение сайта'),
        ),
    ]
