# Generated by Django 2.0 on 2017-12-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20171208_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='К примеру, "Буднии дни с ПН по ЧТ', max_length=250, verbose_name='Период')),
                ('condition_1', models.CharField(help_text='С 9:00 до 17:00 – 500 руб.\\час', max_length=200, verbose_name='Время и цена(Условие 1)')),
                ('condition_2', models.CharField(blank=True, help_text='с 17:00 до 09:00 – 1000 руб.\\час', max_length=200, null=True, verbose_name='Время и цена(Условие 2)')),
                ('condition_3', models.CharField(blank=True, help_text='с 17:00 до 09:00 – 1000 руб.\\час', max_length=200, null=True, verbose_name='Время и цена(Условие 3)')),
                ('note', models.CharField(blank=True, help_text='К примеру, "*свыше 6 чел, за каждого последующего 100 руб.\\час".', max_length=250, null=True, verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'db_table': 'sauna_schedule',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='Наименование услуги')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'db_table': 'sauna_service',
            },
        ),
    ]
