# Generated by Django 2.0 on 2017-12-08 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20171208_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='name',
            field=models.CharField(default='Main Settings', max_length=100, verbose_name='Имя настройки'),
        ),
    ]
