# Generated by Django 2.0 on 2017-12-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20171208_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='contacts',
        ),
        migrations.AddField(
            model_name='settings',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='settings',
            name='addressHref',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ссылка перенаправляющая на карты(Google/Yandex)'),
        ),
        migrations.AddField(
            model_name='settings',
            name='contacts_phone',
            field=models.CharField(blank=True, max_length=90, null=True, verbose_name='Телефон/ы на странице контактов'),
        ),
        migrations.AddField(
            model_name='settings',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='settings',
            name='footer_phone',
            field=models.CharField(blank=True, max_length=90, null=True, verbose_name='Телефон в нижней части страници'),
        ),
        migrations.AddField(
            model_name='settings',
            name='map',
            field=models.TextField(blank=True, help_text='Карта, которая отображается в контактах', max_length=1024, null=True, verbose_name='Окно с картой'),
        ),
        migrations.DeleteModel(
            name='Contacts',
        ),
    ]
