# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-09 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_settings_footer_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='footer_copyright',
            field=models.CharField(blank=True, default='Copyright by Ideal', max_length=20, null=True, verbose_name='Текст копирайта в нижней части страницы'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='address',
            field=models.CharField(blank=True, default='ул.Техническая, 1', max_length=200, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='addressHref',
            field=models.CharField(blank=True, default='https://www.google.ru/maps/place/%D1%83%D0%BB.+%D0%9F%D0%B5%D1%80%D0%B2%D0%BE%D0%BC%D0%B0%D0%B9%D1%81%D0%BA%D0%B0%D1%8F,+77,+%D0%95%D0%BA%D0%B0%D1%82%D0%B5%D1%80%D0%B8%D0%BD%D0%B1%D1%83%D1%80%D0%B3,+%D0%A1%D0%B2%D0%B5%D1%80%D0%B4%D0%BB%D0%BE%D0%B2%D1%81%D0%BA%D0%B0%D1%8F+%D0%BE%D0%B1%D0%BB.,+620062/@56.8459859,60.639357,17z/data=!3m1!4b1!4m5!3m4!1s0x43c16c2be5298e21:0x77522d799d8f3f75!8m2!3d56.8459859!4d60.6415457', max_length=500, null=True, verbose_name='Ссылка перенаправляющая на карты(Google/Yandex)'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='footer_phone',
            field=models.CharField(blank=True, default='+7 (343) 111-11-11', max_length=90, null=True, verbose_name='Телефон в нижней части страници'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='name',
            field=models.CharField(default='Глобальная настройка', max_length=100, verbose_name='Имя настройки'),
        ),
    ]
