# Generated by Django 2.0 on 2017-12-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20171208_1844'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Страница "Главная"', 'verbose_name_plural': 'Страница "Главная"'},
        ),
        migrations.AlterModelOptions(
            name='saunapage',
            options={'verbose_name': 'Сауна', 'verbose_name_plural': 'Сауны'},
        ),
        migrations.AlterField(
            model_name='homepage',
            name='jumbotron_video',
            field=models.TextField(blank=True, help_text='Элемент идущий после главного заголовка - это может быть картинка, либо видео и т.д. Будет выбрано либо видео, либо изображение.', max_length=1024, null=True, verbose_name='Джамботрон - видео'),
        ),
    ]
