# Generated by Django 2.0 on 2017-12-08 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20171208_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricespage',
            name='slug',
            field=models.SlugField(default='', help_text='К примеру, "my_new_awesome_hall"', max_length=70, verbose_name='Название ссылки к странице сауны'),
        ),
    ]
