# Generated by Django 2.0 on 2017-12-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_pricespage_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactspage',
            name='content',
            field=models.TextField(blank=True, max_length=16000, null=True, verbose_name='Контент страницы'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=models.TextField(blank=True, max_length=16000, null=True, verbose_name='Контент страницы'),
        ),
        migrations.AlterField(
            model_name='pricespage',
            name='content',
            field=models.TextField(blank=True, max_length=16000, null=True, verbose_name='Контент страницы'),
        ),
        migrations.AlterField(
            model_name='saunapage',
            name='content',
            field=models.TextField(blank=True, max_length=16000, null=True, verbose_name='Контент страницы'),
        ),
        migrations.AlterField(
            model_name='servicespage',
            name='content',
            field=models.TextField(blank=True, max_length=16000, null=True, verbose_name='Контент страницы'),
        ),
    ]
