# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-09 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20171209_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactspage',
            name='phone_1',
            field=models.CharField(blank=True, default='+7 (343) 36-16-911', max_length=90, null=True, verbose_name='Телефон 2'),
        ),
        migrations.AddField(
            model_name='contactspage',
            name='phone_2',
            field=models.CharField(blank=True, default='+7 (922) 18-16-911', max_length=90, null=True, verbose_name='Телефон 1'),
        ),
    ]
