# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-09 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_contactspage_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactspage',
            name='main_title',
            field=models.CharField(blank=True, help_text='Заголовок(можно обернуть в ссылку)', max_length=500, null=True, verbose_name='Заголовок страницы'),
        ),
        migrations.AddField(
            model_name='pricespage',
            name='main_title',
            field=models.CharField(blank=True, help_text='Заголовок(можно обернуть в ссылку)', max_length=500, null=True, verbose_name='Заголовок страницы'),
        ),
        migrations.AddField(
            model_name='saunapage',
            name='main_title',
            field=models.CharField(blank=True, help_text='Заголовок(можно обернуть в ссылку)', max_length=500, null=True, verbose_name='Заголовок страницы'),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='main_title',
            field=models.CharField(blank=True, help_text='Заголовок(можно обернуть в ссылку)', max_length=500, null=True, verbose_name='Заголовок страницы'),
        ),
        migrations.AlterField(
            model_name='contactspage',
            name='title',
            field=models.CharField(help_text='Название страницы во вкладке', max_length=100, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='main_title',
            field=models.CharField(blank=True, help_text='Заголовок(можно обернуть в ссылку)', max_length=500, null=True, verbose_name='Заголовок страницы'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='title',
            field=models.CharField(help_text='Название страницы во вкладке', max_length=100, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='pricespage',
            name='title',
            field=models.CharField(help_text='Название страницы во вкладке', max_length=100, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='saunapage',
            name='title',
            field=models.CharField(help_text='Название страницы во вкладке', max_length=100, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='servicespage',
            name='title',
            field=models.CharField(help_text='Название страницы во вкладке', max_length=100, verbose_name='Заголовок'),
        ),
    ]
