# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-28 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0007_remove_album_album_images'),
        ('pages', '0013_remove_saunapage_main_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='saunapage',
            name='thumb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sauna_thumb', to='album.AlbumImage', verbose_name='Превью сауны'),
        ),
        migrations.AlterField(
            model_name='contactspage',
            name='content',
            field=models.TextField(blank=True, help_text='Заголовок - h3, параграф - p.', max_length=16000, null=True, verbose_name='Контент страницы'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=models.TextField(blank=True, help_text='Заголовок - h3, параграф - p.', max_length=16000, null=True, verbose_name='Контент страницы'),
        ),
        migrations.AlterField(
            model_name='pricespage',
            name='content',
            field=models.TextField(blank=True, help_text='Заголовок - h3, параграф - p.', max_length=16000, null=True, verbose_name='Контент страницы'),
        ),
        migrations.AlterField(
            model_name='saunapage',
            name='content',
            field=models.TextField(blank=True, help_text='Заголовок - h3, параграф - p.', max_length=16000, null=True, verbose_name='Контент страницы'),
        ),
        migrations.AlterField(
            model_name='servicespage',
            name='content',
            field=models.TextField(blank=True, help_text='Заголовок - h3, параграф - p.', max_length=16000, null=True, verbose_name='Контент страницы'),
        ),
    ]
